#!/bin/sh

rm *.dat
echo Running valgrind and redirecting output to \"output_valgrind.txt\"
valgrind --tool=memcheck --leak-check=yes --show-reachable=yes  AMaLGaM-Full -v -r -s 7 040 -115 -100 0 0.35 776 1 0.9 1.0 1000000 1e-10 100 0.0 >& output_valgrind.txt
